src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordUpdateView,
    AccountUpdateView
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordUpdateView.as_view(), name='password'),

]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

import debug_toolbar


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path
from quiz.views import TestDetailView, TestListView, TestResultCreateView, TestResultUpdateView, TestResultDetailsView, \
  TestQuestionDetailsView, LeaderboardView

app_name = 'quizes'
urlpatterns = [
  path('', TestListView.as_view(), name='list'),
  path('leaderboard/', LeaderboardView.as_view(), name='leaderboard'),
  path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
  path('<uuid:uuid>/runs/create', TestResultCreateView.as_view(), name='create_run'),
  path('<uuid:uuid>/runs/<str:run_uuid>/continue', TestResultUpdateView.as_view(), name='continue_run'),
  path('<uuid:uuid>/runs/<str:run_uuid>/details', TestResultDetailsView.as_view(), name='run'),
  path('<uuid:uuid>/runs/<str:run_uuid>/questions/<int:order_number>', TestQuestionDetailsView.as_view(),
       name='question'),

]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QUIZZY</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold ">
  <div class="container">

  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'quizes:list' %}">Quizes<span class="sr-only"></span></a>
      </li>
    </ul>

    <ul class="navbar-nav ">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>

            {%  if user.is_authenticated %}
{#                <li class="nav-item">#}
{#                    <img alt="Profile pic" width="35" height="35" class="rounded-circle" src="{{ user.image.url }}">#}
{#                </li>#}

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'quizes:leaderboard' %}">Leaderboard</a>
                  </li>

            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
            {% endif %}

    </ul>

  </div>
  </div>
</nav>

<div class="container">

        {% include 'includes/messages.html' %}

        <div class="border rounded text-center p-3 m-3 bg-light text-dark">
            {% block header %}
                <h1> ¡Quiz! </h1>
            {% endblock %}
        </div>

        {% block main %}
        {% endblock %}
</div>


</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block main %}

    <h5>Welcome to the quiz app!</h5>

{% endblock %}